"""
Data from: 
https://en.wikipedia.org/wiki/List_of_country_groupings
https://github.com/rapomon/geojson-places/tree/master
https://aric.adb.org/integrationindicators/groupings
https://worldpopulationreview.com/country-rankings/western-countries
https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups
"""

regions = [
    {
        'id': '1',
        'grouping_code': 'AF',
        'grouping_name': 'Africa',
        'countries': [
            'Algeria',
            'Angola',
            'Benin',
            'Botswana',
            'Burkina Faso',
            'Burundi',
            'Cameroon',
            'Cape Verde',
            'Central African Republic',
            'Chad',
            'Comoros',
            'Democratic Republic of the Congo',
            'Djibouti',
            'Egypt',
            'Equatorial Guinea',
            'Eritrea',
            'Ethiopia',
            'Gabon',
            'Gambia',
            'Ghana',
            'Guinea',
            'Guinea Bissau',
            'Ivory Coast',
            'Kenya',
            'Lesotho',
            'Liberia',
            'Libya',
            'Madagascar',
            'Malawi',
            'Mali',
            'Mauritania',
            'Mauritius',
            'Morocco',
            'Mozambique',
            'Namibia',
            'Niger',
            'Nigeria',
            'Republic of the Congo',
            'Rwanda',
            'S. Sudan',
            'Saint Helena',
            'Sao Tome and Principe',
            'Senegal',
            'Seychelles',
            'Sierra Leone',
            'Somalia',
            'South Africa',
            'Sudan',
            'Swaziland',
            'Togo',
            'Tunisia',
            'Uganda',
            'United Republic of Tanzania',
            'Western Sahara',
            'Zambia',
            'Zimbabwe'
            ]
    },
    {
        'id': '2',
        'grouping_code': 'America',
        'grouping_name': 'America',
        'countries': [
            'Anguilla',
            'Antigua and Barbuda',
            'Argentina',
            'Aruba',
            'Barbados',
            'Belize',
            'Bermuda',
            'Bolivia',
            'Brazil',
            'British Virgin Islands',
            'Canada',
            'Cayman Islands',
            'Chile',
            'Colombia',
            'Costa Rica',
            'Curaçao',
            'Dominica',
            'Dominican Republic',
            'Ecuador',
            'El Salvador',
            'Falkland Islands',
            'France',
            'Georgia',
            'Greenland',
            'Grenada',
            'Guatemala',
            'Guyana',
            'Haiti',
            'Honduras',
            'Jamaica',
            'Mexico',
            'Montserrat',
            'Nicaragua',
            'Panama',
            'Paraguay',
            'Peru',
            'Puerto Rico',
            'Saint Barthelemy',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Martin',
            'Saint Pierre and Miquelon',
            'Saint Vincent and the Grenadines',
            'Sint Maarten',
            'Suriname',
            'The Bahamas',
            'Trinidad and Tobago',
            'Turks and Caicos Islands',
            'United States of America',
            'United States Virgin Islands',
            'Uruguay',
            'US Naval Base Guantanamo Bay',
            'Venezuela'
        ]
    },
    {
        'id': '3',
        'grouping_code': 'APAC',
        'grouping_name': 'Asia-Pacific',
        'countries' : [
            'American Samoa',
            'Australia',
            'Bangladesh',
            'Bhutan',
            'Brunei',
            'Cambodia',
            'China',
            'Cook Islands',
            'East Timor',
            'Federated States of Micronesia',
            'Fiji',
            'French Polynesia',
            'Guam',
            'Hong Kong S.A.R.',
            'India',
            'Indonesia',
            'Japan',
            'Kiribati',
            'Laos',
            'Macau S.A.R',
            'Malaysia',
            'Maldives',
            'Marshall Islands',
            'Mongolia',
            'Myanmar',
            'Nauru',
            'Nepal',
            'New Caledonia',
            'New Zealand',
            'Niue',
            'Norfolk Island',
            'North Korea',
            'Northern Mariana Islands',
            'Pakistan',
            'Palau',
            'Papua New Guinea',
            'Philippines',
            'Pitcairn Islands',
            'Russia',
            'Samoa',
            'Singapore',
            'Solomon Islands',
            'South Korea',
            'Sri Lanka',
            'Taiwan',
            'Thailand',
            'Tokelau',
            'Tonga',
            'Tuvalu',
            'Vanuatu',
            'Vietnam',
            'Wallis and Futuna'
        ]
    },
    {
        'id': '4',
        'grouping_code': 'Asia',
        'grouping_name': 'Asia',
        'countries': [
            'Afghanistan',
            'Armenia',
            'Azerbaijan',
            'Bahrain',
            'Bangladesh',
            'Bhutan',
            'British Indian Ocean Territory',
            'Brunei',
            'Cambodia',
            'China',
            'Dhekelia Sovereign Base Area',
            'East Timor',
            'Gaza Strip',
            'Georgia',
            'Hong Kong',
            'Hong Kong S.A.R.',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Israel',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kuwait',
            'Kyrgyzstan',
            'Laos',
            'Lebanon',
            'Macau',
            'Macau S.A.R',
            'Malaysia',
            'Maldives',
            'Mongolia',
            'Myanmar',
            'Nepal',
            'North Korea',
            'Oman',
            'Pakistan',
            'Philippines',
            'Qatar',
            'Russia',
            'Saudi Arabia',
            'Singapore',
            'South Korea',
            'Sri Lanka',
            'Syria',
            'Taiwan',
            'Tajikistan',
            'Thailand',
            'Turkey',
            'Turkmenistan',
            'United Arab Emirates',
            'Uzbekistan',
            'Vietnam',
            'Yemen'
        ]
    },
    {
        'id': '5',
        'grouping_code': 'ASEAN',
        'grouping_name': 'Association of Southeast Asian Nations',
        'countries': [
            'Brunei',      
            'Cambodia',
            'China',       
            'Indonesia',
            'Japan',       
            'Laos',
            'Malaysia',    
            'Myanmar',
            'Philippines', 
            'Singapore',
            'South Korea', 
            'Thailand',
            'Vietnam'
        ]
    },
    {
        'id': '6',
        'grouping_code': 'Central Asia',
        'grouping_name': 'Central Asia',
        'countries': [
            'Armenia',
            'Azerbaijan',
            'Georgia',
            'Kazakhstan',
            'Tajikistan',
            'Turkmenistan',
            'Uzbekistan'
        ]
    },
    {
        'id': '7',
        'grouping_code': 'East Asia',
        'grouping_name': 'East Asia',
        'countries': [
            'China',
            'Hong Kong',
            'Hong Kong S.A.R.'
            'Japan',
            'Mongolia',
            'South Korea',
            'Taiwan'
        ]
    },
    {
        'id': '8',
        'grouping_code': 'EU',
        'grouping_name': 'Europe',
        'countries': [
            'Aland',
            'Albania',
            'Andorra',
            'Armenia',
            'Austria',
            'Azerbaijan',
            'Belarus',
            'Belgium',
            'Bosnia and Herzegovina',
            'Bulgaria',
            'Croatia',
            'Czech Republic',
            'Denmark',
            'Dhekelia Sovereign Base Area',
            'Estonia',
            'Faroe Islands',
            'Finland',
            'France',
            'Georgia',
            'Germany',
            'Gibraltar',
            'Greece',
            'Guernsey',
            'Hungary',
            'Iceland',
            'Ireland',
            'Isle of Man',
            'Italy',
            'Jersey',
            'Kazakhstan',
            'Kosovo',
            'Latvia',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Macedonia',
            'Malta',
            'Moldova',
            'Monaco',
            'Montenegro',
            'Netherlands',
            'Norway',
            'Poland',
            'Portugal',
            'Republic of Serbia',
            'Romania',
            'Russia',
            'San Marino',
            'Slovakia',
            'Slovenia',
            'Spain',
            'Sweden',
            'Switzerland',
            'Turkey',
            'Ukraine',
            'United Kingdom',
            'Vatican'
        ]
    },
    {
        'id': '9',
        'grouping_code': 'Middle East',
        'grouping_name': 'Middle East',
        'countries': [
            'Bahrain',              
            'Egypt',
            'Iran',                 
            'Iraq',
            'Israel',               
            'Jordan',
            'Kuwait',               
            'Lebanon',
            'Libya',                
            'Oman',
            'Qatar',                
            'Saudi Arabia',
            'Syria',                
            'Turkey',
            'United Arab Emirates', 
            'Yemen'
        ]
    },
    {
        'id': '10',
        'grouping_code': 'NA',
        'grouping_name': 'North America',
        'countries': [
            'Anguilla',
            'Antigua and Barbuda',
            'Aruba',
            'Barbados',
            'Belize',
            'Bermuda',
            'British Virgin Islands',
            'Canada',
            'Cayman Islands',
            'Costa Rica',
            'Curaçao',
            'Dominica',
            'Dominican Republic',
            'El Salvador',
            'Greenland',
            'Grenada',
            'Guatemala',
            'Haiti',
            'Honduras',
            'Jamaica',
            'Mexico',
            'Montserrat',
            'Nicaragua',
            'Panama',
            'Puerto Rico',
            'Saint Barthelemy',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Martin',
            'Saint Pierre and Miquelon',
            'Saint Vincent and the Grenadines',
            'Sint Maarten',
            'The Bahamas',
            'Trinidad and Tobago',
            'Turks and Caicos Islands',
            'United States Minor Outlying Islands',
            'United States of America',
            'United States Virgin Islands',
            'US Naval Base Guantanamo Bay'
        ]
    },
    {
        'id': '11',
        'grouping_code': 'OC',
        'grouping_name': 'Oceania',
        'countries': [
            'American Samoa',
            'Australia',
            'Cook Islands',
            'Federated States of Micronesia',
            'Fiji',
            'French Polynesia',
            'Guam',
            'Kiribati',
            'Marshall Islands',
            'Nauru',
            'New Caledonia',
            'New Zealand',
            'Niue',
            'Norfolk Island',
            'Northern Mariana Islands',
            'Palau',
            'Papua New Guinea',
            'Pitcairn Islands',
            'Samoa',
            'Solomon Islands',
            'Tokelau',
            'Tonga',
            'Tuvalu',
            'United States Minor Outlying Islands',
            'Vanuatu',
            'Wallis and Futuna'
        ]
    },
    {
        'id': '12',
        'grouping_code': 'SA',
        'grouping_name': 'South America',
        'countries': [
            'Argentina',        
            'Bolivia',
            'Brazil',           
            'Chile',
            'Colombia',         
            'Ecuador',
            'Falkland Islands', 
            'Guyana',
            'Paraguay',         
            'Peru',
            'Suriname',         
            'Uruguay',
            'Venezuela'
        ]
    },
    {
        'id': '13',
        'grouping_code': 'SAARC',
        'grouping_name': 'South Asia',
        'countries': [
            'Afghanistan',
            'Bangladesh',
            'Bhutan',
            'India',
            'Maldives',
            'Nepal',
            'Pakistan',
            'Sri Lanka'
        ]
    },
    {
        'id': '14',
        'grouping_code': 'SEA',
        'grouping_name': 'South-East Asia',
        'countries': [
            'Brunei',     
            'Cambodia',
            'East Timor', 
            'Indonesia',
            'Laos',       
            'Malaysia',
            'Myanmar',    
            'Philippines',
            'Singapore',  
            'Thailand',
            'Vietnam'
        ]
    },
    {
        'id': '15',
        'grouping_code': 'Western',
        'grouping_name': 'Western',
        'countries': [
            'Andorra', 
            'Antigua and Barbuda', 
            'Argentina', 
            'Australia', 
            'Austria', 
            'Bahamas', 
            'Barbados', 
            'Belgium', 
            'Canada', 
            'Chile', 
            'Costa Rica', 
            'Croatia', 
            'Cyprus', 
            'Czech Republic', 
            'Denmark', 
            'Estonia', 
            'Finland', 
            'France', 
            'Germany', 
            'Greece', 
            'Hungary', 
            'Iceland', 
            'Ireland', 
            'Italy', 
            'Latvia', 
            'Liechtenstein', 
            'Lithuania', 
            'Luxembourg', 
            'Malta', 
            'Monaco', 
            'Netherlands', 
            'New Zealand', 
            'Panama', 
            'Poland', 
            'Portugal', 
            'Slovakia', 
            'Slovenia', 
            'Spain', 
            'Sweden',
            'Switzerland', 
            'Trinidad and Tobago', 
            'United Kingdom',
            'United States', 
            'Uruguay', 
            'Vatican City'
        ]
    }
]